# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: ['ubuntu-latest', 'windows-latest  ', 'debain-latest', 'macos-latest']
    runs-on: ${{matrix.platform}}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      shell: bash
